Directory: /cluster/home/juliemey/master | Name of job: Modelltrening | Job ID: 19943860
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
scipy 1.8.1 requires numpy<1.25.0,>=1.17.3, but you have numpy 1.26.4 which is incompatible.
Kj√∏rer python program
shape of imgs torch.Size([128, 3, 64, 64]) shape of class torch.Size([128, 1])
tensor saved, shape: torch.Size([3, 64, 64])
torch.Size([28709, 512]) torch.Size([28709, 1])
shape of images: torch.Size([16, 1, 64, 64]) shape of classes: torch.Size([16, 1]) shape of img embeds:  torch.Size([16, 512])
1
1
2
2
4
4
4
4
8
8
4
4
2
2
1
1
2
2
4
4
4
4
8
8
4
4
2
2
Training progress:   0%|[38;2;0;255;0m          [0m| 0/50 [00:00<?, ?it/s]
Epoch 1/50:   0%|[38;2;0;85;0m          [0m| 0/1795 [00:00<?, ?it/s][A
                                                    [ATraining progress:   0%|[38;2;0;255;0m          [0m| 0/50 [00:05<?, ?it/s]
Traceback (most recent call last):
  File "/cluster/home/juliemey/master/ddpm_OFFICIAL_resnet+label2.py", line 699, in <module>
    training_loop(model, loader, n_epochs, device, display=False, store_path="ddpm_resnet_label22.pt")
  File "/cluster/home/juliemey/master/ddpm_OFFICIAL_resnet+label2.py", line 667, in training_loop
    eta_theta = ddpm.backward(noisy_imgs, t.reshape(n, -1), labels, clss)
  File "/cluster/home/juliemey/master/ddpm_OFFICIAL_resnet+label2.py", line 371, in backward
    return self.cond_unet(x,t, cond, clss)
  File "/cluster/apps/eb/software/PyTorch/1.12.0-foss-2022a-CUDA-11.7.0/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/cluster/home/juliemey/master/ddpm_OFFICIAL_resnet+label2.py", line 613, in forward
    out1 = self.b1(x + self.te1(t).reshape(n, -1, 1, 1), label) 
  File "/cluster/apps/eb/software/PyTorch/1.12.0-foss-2022a-CUDA-11.7.0/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/cluster/home/juliemey/master/ddpm_OFFICIAL_resnet+label2.py", line 413, in forward
    x = self.attn(x, label)
  File "/cluster/apps/eb/software/PyTorch/1.12.0-foss-2022a-CUDA-11.7.0/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/cluster/home/juliemey/master/ddpm_OFFICIAL_resnet+label2.py", line 303, in forward
    x = self.transformer(x, context)
  File "/cluster/apps/eb/software/PyTorch/1.12.0-foss-2022a-CUDA-11.7.0/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/cluster/home/juliemey/master/ddpm_OFFICIAL_resnet+label2.py", line 287, in forward
    x = self.attn_cross(self.norm2(x), context=context) + x #size: [16, 256, 64] (batch, context_dim, h*w)
  File "/cluster/apps/eb/software/PyTorch/1.12.0-foss-2022a-CUDA-11.7.0/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/cluster/home/juliemey/master/ddpm_OFFICIAL_resnet+label2.py", line 249, in forward
    Q = self.query(context)
  File "/cluster/apps/eb/software/PyTorch/1.12.0-foss-2022a-CUDA-11.7.0/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/cluster/apps/eb/software/PyTorch/1.12.0-foss-2022a-CUDA-11.7.0/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (16x512 and 1x1)
